In [8]:
# ein Modul importieren und nutzen

import string

In [ ]:
string.ascii_lowercase   # dot notation, tab completion

In [9]:
print(f'Die ASCII Kleinbuchstaben lauten {string.ascii_lowercase}.')

Die ASCII Kleinbuchstaben lauten abcdefghijklmnopqrstuvwxyz.

In [10]:
print(string.capwords('schreibe alle anfangsbuchstaben groß'))

Schreibe Alle Anfangsbuchstaben Groß

In [11]:
help(string)

Help on package string:

NAME
    string - A collection of string constants.

DESCRIPTION
    Public module variables:

    whitespace -- a string containing all ASCII whitespace
    ascii_lowercase -- a string containing all ASCII lowercase letters
    ascii_uppercase -- a string containing all ASCII uppercase letters
    ascii_letters -- a string containing all ASCII letters
    digits -- a string containing all ASCII decimal digits
    hexdigits -- a string containing all ASCII hexadecimal digits
    octdigits -- a string containing all ASCII octal digits
    punctuation -- a string containing all ASCII punctuation characters
    printable -- a string containing all ASCII characters considered printable

PACKAGE CONTENTS
    templatelib

CLASSES
    builtins.object
        Formatter
        Template

    class Formatter(builtins.object)
     |  Methods defined here:
     |
     |  check_unused_args(self, used_args, args, kwargs)
     |
     |  convert_field(self, value, conversion)
     |
     |  format(self, format_string, /, *args, **kwargs)
     |
     |  format_field(self, value, format_spec)
     |
     |  get_field(self, field_name, args, kwargs)
     |      # given a field_name, find the object it references.
     |      #  field_name:   the field being looked up, e.g. "0.name"
     |      #                 or "lookup[3]"
     |      #  used_args:    a set of which args have been used
     |      #  args, kwargs: as passed in to vformat
     |
     |  get_value(self, key, args, kwargs)
     |
     |  parse(self, format_string)
     |      # returns an iterable that contains tuples of the form:
     |      # (literal_text, field_name, format_spec, conversion)
     |      # literal_text can be zero length
     |      # field_name can be None, in which case there's no
     |      #  object to format and output
     |      # if field_name is not None, it is looked up, formatted
     |      #  with format_spec and conversion and then used
     |
     |  vformat(self, format_string, args, kwargs)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables
     |
     |  __weakref__
     |      list of weak references to the object

    class Template(builtins.object)
     |  Template(template)
     |
     |  A string class for supporting $-substitutions.
     |
     |  Methods defined here:
     |
     |  __init__(self, template)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  get_identifiers(self)
     |
     |  is_valid(self)
     |
     |  safe_substitute(self, mapping={}, /, **kws)
     |
     |  substitute(self, mapping={}, /, **kws)
     |
     |  ----------------------------------------------------------------------
     |  Class methods defined here:
     |
     |  __init_subclass__()
     |      This method is called when a class is subclassed.
     |
     |      The default implementation does nothing. It may be
     |      overridden to extend subclasses.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables
     |
     |  __weakref__
     |      list of weak references to the object
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  braceidpattern = None
     |
     |  delimiter = '$'
     |
     |  flags = re.IGNORECASE
     |
     |  idpattern = '(?a:[_a-z][_a-z0-9]*)'
     |
     |  pattern = re.compile('\n            \\$(?:\n              ...identifie...

FUNCTIONS
    capwords(s, sep=None)
        capwords(s [,sep]) -> string

        Split the argument into words using split, capitalize each
        word using capitalize, and join the capitalized words using
        join.  If the optional second argument sep is absent or None,
        runs of whitespace characters are replaced by a single space
        and leading and trailing whitespace are removed, otherwise
        sep is used to split and join the words.

DATA
    __all__ = ['ascii_letters', 'ascii_lowercase', 'ascii_uppercase', 'cap...
    ascii_letters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
    ascii_lowercase = 'abcdefghijklmnopqrstuvwxyz'
    ascii_uppercase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    digits = '0123456789'
    hexdigits = '0123456789abcdefABCDEF'
    octdigits = '01234567'
    printable = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTU...
    punctuation = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'
    whitespace = ' \t\n\r\x0b\x0c'

FILE
    /lib/python314.zip/string/__init__.py

In [12]:
# nur bestimmten Aspekt importieren

from string import ascii_letters

print(f'Die ASCII Buchstaben sind {ascii_letters}')

Die ASCII Buchstaben sind abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ

In [14]:
# ein Modul installieren
# https://pymarc.readthedocs.io/en/latest/

import pymarc  # gibt es aber offenbar noch nicht

<class 'ModuleNotFoundError'>: No module named 'pymarc'

In [15]:
# pip - python package index, benötigt Internetverbindung, wird lokal bzw. in der Jupyter environment installiert

%pip install pymarc

In [16]:
import pymarc

In [ ]:
# import mit Alias

import pandas as pd    # Konvention, siehe auch Dokumentation
import numpy as np
import matplotlib as plt

In [17]:
# Pandas library: tabellarische Daten einlesen

import pandas as pd

In [18]:
df = pd.read_csv('data/2011_circ.csv')  # comma separated values, Pfad zu der Datei, die gelesen werden soll, als string

In [21]:
df.head()  # erste 5 Zeilen werden ausgegeben, ansonsten in die Klammer andere Zahl eingeben

,branch,address,city,zip code,january,february,march,april,may,june,july,august,september,october,november,december,ytd
0,Albany Park,5150 N. Kimball Ave.,Chicago,60625.0,8427,7023,9702,9344,8865,11650,11778,11306,10466,10997,10567,9934,120059
1,Altgeld,13281 S. Corliss Ave.,Chicago,60827.0,1258,708,854,804,816,870,713,480,702,927,787,692,9611
2,Archer Heights,5055 S. Archer Ave.,Chicago,60632.0,8104,6899,9329,9124,7472,8314,8116,9177,9033,9709,8809,7865,101951
3,Austin,5615 W. Race Ave.,Chicago,60644.0,1755,1316,1942,2200,2133,2359,2080,2405,2417,2571,2233,2116,25527
4,Austin-Irving,6100 W. Irving Park Rd.,Chicago,60634.0,12593,11791,14807,14382,11754,14402,14605,15164,14306,15357,14069,12404,165634

In [22]:
df.info()   # Info über den dataframe: Anzahl der Spalten und Zeilen, Datentypen

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   branch     80 non-null     str
 1   address    80 non-null     str
 2   city       80 non-null     str
 3   zip code   80 non-null     float64
 4   january    80 non-null     int64
 5   february   80 non-null     int64
 6   march      80 non-null     int64
 7   april      80 non-null     int64
 8   may        80 non-null     int64
 9   june       80 non-null     int64
 10  july       80 non-null     int64
 11  august     80 non-null     int64
 12  september  80 non-null     int64
 13  october    80 non-null     int64
 14  november   80 non-null     int64
 15  december   80 non-null     int64
 16  ytd        80 non-null     int64
dtypes: float64(1), int64(13), str(3)
memory usage: 9.8 KB

In [23]:
df.columns   # Spaltennamen

Index(['branch', 'address', 'city', 'zip code', 'january', 'february', 'march',
       'april', 'may', 'june', 'july', 'august', 'september', 'october',
       'november', 'december', 'ytd'],
      dtype='str')

In [24]:
# statistische Zusammenfassung der numerischen Spalten

df.describe()

,zip code,january,february,march,april,may,june,july,august,september,october,november,december,ytd
count,80.000000,80.000000,80.000000,80.00000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.00000,80.000000
mean,60632.675000,7216.175000,6247.162500,8367.36250,8209.225000,7551.725000,8581.125000,8708.887500,8918.550000,8289.975000,9033.437500,8431.112500,7622.73750,97177.475000
std,28.001254,10334.622299,8815.945718,11667.93342,11241.223544,10532.352671,10862.742953,10794.030461,11301.149192,10576.005552,10826.494853,10491.875418,9194.44616,125678.282307
min,60605.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.00000,9218.000000
25%,60617.000000,2388.500000,1979.250000,2708.50000,2864.250000,2678.500000,2953.750000,3344.750000,3310.500000,3196.750000,3747.000000,3168.000000,3049.75000,37119.250000
50%,60629.000000,5814.500000,5200.000000,6468.50000,6286.000000,5733.000000,6764.500000,6194.000000,6938.500000,6599.500000,7219.500000,6766.000000,5797.00000,73529.000000
75%,60643.000000,9021.000000,8000.000000,10737.00000,10794.250000,9406.250000,10852.750000,11168.000000,11291.750000,10520.000000,11347.500000,10767.000000,9775.00000,124195.750000
max,60827.000000,79210.000000,67574.000000,89122.00000,88527.000000,82581.000000,82100.000000,80219.000000,85193.000000,81400.000000,82236.000000,79702.000000,68856.00000,966720.000000

In [26]:
# Übung: Alias

import string as s
numbers = s.digits
print(numbers)

0123456789

In [27]:
numbers = string.digits
print(numbers)

0123456789

In [29]:
# Übung: passende Bibliothek finden

year = 1971
month = 8
day = 26

import datetime

iso_date = datetime.date(year, month, day).isoformat()
print(iso_date)

1971-08-26