In [36]:
# Alle Daten in einem Dataframe zusammenführen (vgl. Übung 8)

# importiere Module
import glob
import pandas as pd

dfs = []   # initializiere neue (leere) Liste

for csv in sorted(glob.glob('data/*_circ.csv')):
    year_number = csv[5:9]                  # extrahiere Jahreszahl aus Dateinamen
    data = pd.read_csv(csv) 
    data['year_header'] = year_number       # generiere in jedem einzelnen Datensatz neue Spalte einfach durch Zuweisung
    dfs.append(data)                        # jeder einzelne Datensatz wird an die Liste angehängt

df = pd.concat(dfs, ignore_index=True)      # mit concat wird aus der Liste ein neuer einheitlicher Datensatz generiert

df.head(3)    # erste 3 Zeilen

,branch,address,city,zip code,january,february,march,april,may,june,july,august,september,october,november,december,ytd,year_header
0,Albany Park,5150 N. Kimball Ave.,Chicago,60625.0,8427,7023,9702,9344,8865,11650,11778,11306,10466,10997,10567,9934,120059,2011
1,Altgeld,13281 S. Corliss Ave.,Chicago,60827.0,1258,708,854,804,816,870,713,480,702,927,787,692,9611,2011
2,Archer Heights,5055 S. Archer Ave.,Chicago,60632.0,8104,6899,9329,9124,7472,8314,8116,9177,9033,9709,8809,7865,101951,2011

In [37]:
df.tail()  # letzte 5 Zeilen

,branch,address,city,zip code,january,february,march,april,may,june,july,august,september,october,november,december,ytd,year_header
958,Chinatown,2100 S. Wentworth Ave.,Chicago,60616.0,4795,4258,5316,5343,4791,5367,5477,5362,4991,4847,4035,3957,58539,2022
959,Brainerd,1350 W. 89th St.,Chicago,60620.0,255,264,370,386,399,421,337,373,361,276,256,201,3899,2022
960,Brighton Park,4314 S. Archer Ave.,Chicago,60632.0,1394,1321,1327,1705,1609,1578,1609,1512,1425,1603,1579,1278,17940,2022
961,South Chicago,9055 S. Houston Ave.,Chicago,60617.0,496,528,739,775,587,804,720,883,681,697,799,615,8324,2022
962,Chicago Bee,3647 S. State St.,Chicago,60609.0,799,543,709,803,707,931,778,770,714,835,718,788,9095,2022

In [38]:
# bestimmte Zeilen anschauen (slicing)

df[50:60]

,branch,address,city,zip code,january,february,march,april,may,june,july,august,september,october,november,december,ytd,year_header
50,Near North,310 W. Division St.,Chicago,60610.0,11032,10021,12911,12621,12437,13988,13955,14729,13989,13355,13006,12194,154238,2011
51,North Austin,5724 W. North Ave.,Chicago,60639.0,2481,2045,2674,2832,2202,2694,3302,3225,3160,3074,2796,2272,32757,2011
52,North Pulaski,4300 W. North Ave.,Chicago,60639.0,3848,3176,4111,5066,3885,5105,5916,5512,5349,6386,5952,5372,59678,2011
53,Northtown,6435 N. California Ave.,Chicago,60645.0,10191,8314,11569,11577,10902,14202,15310,14152,11623,12266,12673,12227,145006,2011
54,Oriole Park,7454 W. Balmoral Ave.,Chicago,60656.0,11999,11206,13675,12755,10364,12781,12219,12066,10856,11324,10503,9878,139626,2011
55,Portage-Cragin,5108 W. Belmont Ave.,Chicago,60641.0,9185,7634,9760,10163,7995,9735,10617,11203,10188,11418,10718,9517,118133,2011
56,Pullman,11001 S. Indiana Ave.,Chicago,60628.0,1916,1206,1975,2176,2019,2347,2092,2426,2476,2611,2530,2033,25807,2011
57,Roden,6083 N. Northwest Highway,Chicago,60631.0,6336,5830,7513,6978,6180,8519,8985,7592,6628,7113,6999,6082,84755,2011
58,Rogers Park,6907 N. Clark St.,Chicago,60626.0,10537,9683,13812,13745,13368,18314,20367,19773,18419,18972,17255,16597,190842,2011
59,Roosevelt,1101 W. Taylor St.,Chicago,60607.0,6357,6171,8228,7683,7257,8545,8134,8289,7696,7598,7019,6665,89642,2011

In [39]:
# Spalte auswählen

df['year_header']

0      2011
1      2011
2      2011
3      2011
4      2011
       ...
958    2022
959    2022
960    2022
961    2022
962    2022
Name: year_header, Length: 963, dtype: str

In [40]:
df['year_header'].max()   # statistische Werte der Datenreihe abfragen, z. B. max()

'2022'

In [41]:
# kombinieren

df['year_header'][100:120]    # Spalte und Zeilen, 2x [], Spalte mit header (string), Zeilen mit Indizes

100    2012
101    2012
102    2012
103    2012
104    2012
105    2012
106    2012
107    2012
108    2012
109    2012
110    2012
111    2012
112    2012
113    2012
114    2012
115    2012
116    2012
117    2012
118    2012
119    2012
Name: year_header, dtype: str

In [42]:
ds = df['year_header'][100:120]
type(ds)

pandas.Series

In [43]:
# Spalten mit nicht-numerischen Daten (z. B. strings)

df['branch']

0         Albany Park
1             Altgeld
2      Archer Heights
3              Austin
4       Austin-Irving
            ...
958         Chinatown
959          Brainerd
960     Brighton Park
961     South Chicago
962       Chicago Bee
Name: branch, Length: 963, dtype: str

In [44]:
# Wie viele Zweigstellen gibt es?

df['branch'].unique()   # finde alle unterschiedlichen Werte (jeden nur einmal ausgeben, auch wenn mehrfach vorhanden)

<StringArray>
[                     'Albany Park',                          'Altgeld',
                   'Archer Heights',                           'Austin',
                    'Austin-Irving',                           'Avalon',
                'Back of the Yards',                          'Beverly',
                         'Bezazian',                       'Blackstone',
                         'Brainerd',                    'Brighton Park',
             'Bucktown-Wicker Park',                    'Budlong Woods',
                      'Canaryville',                      'Chicago Bee',
                     'Chicago Lawn',                        'Chinatown',
                         'Clearing',                          'Coleman',
   'Daley, Richard J. - Bridgeport',   'Daley, Richard M. - W Humboldt',
                         'Douglass',                          'Dunning',
                        'Edgebrook',                        'Edgewater',
                        'Gage Park',              'Galewood-Mont Clare',
                   'Garfield Ridge',           'Greater Grand Crossing',
                             'Hall', 'Harold Washington Library Center',
                        'Hegewisch',                    'Humboldt Park',
                     'Independence',                   'Jefferson Park',
                    'Jeffery Manor',                            'Kelly',
                             'King',                  'Legler Regional',
                  'Lincoln Belmont',                     'Lincoln Park',
                   'Little Village',                     'Logan Square',
                           'Lozano',                          'Manning',
                          'Mayfair',                    'McKinley Park',
                            'Merlo',                  'Mount Greenwood',
                       'Near North',                     'North Austin',
                    'North Pulaski',                        'Northtown',
                      'Oriole Park',                   'Portage-Cragin',
                          'Pullman',                            'Roden',
                      'Rogers Park',                        'Roosevelt',
                       'Scottsdale',                     'Sherman Park',
                    'South Chicago',                      'South Shore',
                  'Sulzer Regional',                'Thurgood Marshall',
                            'Toman',                           'Uptown',
                  'Vodak-East Side',                           'Walker',
                      'Water Works',                     'West Belmont',
              'West Chicago Avenue',                   'West Englewood',
                        'West Lawn',                     'West Pullman',
                        'West Town',            'Whitney M. Young, Jr.',
                 'Woodson Regional',               'Wrightwood-Ashburn',
                     'Little Italy',                        'West Loop']
Length: 82, dtype: str

In [45]:
# Teildatensatz betrachten

df.groupby('branch')['ytd'].sum()      # gruppieren nach Kriterium: für jede Zweigstelle (branch) über alle Jahre 
                                       # (impliziert, weil ein großer Datensatz aus den Jahresdatensätzen) die Spalte 'ytd' aufsummiert

branch
Albany Park              1024714
Altgeld                    68358
Archer Heights            803014
Austin                    200107
Austin-Irving            1359700
                          ...
West Pullman              295327
West Town                 922876
Whitney M. Young, Jr.     259680
Woodson Regional          823793
Wrightwood-Ashburn        302285
Name: ytd, Length: 82, dtype: int64

In [46]:
# Sortieren

circ_by_branch = df.groupby('branch')['ytd'].sum()                    # wie oben, Variable zugewiesen
circ_by_branch_sorted = circ_by_branch.sort_values(ascending=False)   # sortieren in absteigender Reihenfolge
circ_by_branch_sorted.head(10)                                       # die ersten 10 Zeilen anzeigen

branch
Harold Washington Library Center    7498041
Sulzer Regional                     5089225
Lincoln Belmont                     1850964
Edgewater                           1668693
Logan Square                        1539816
Rogers Park                         1515964
Bucktown-Wicker Park                1456669
Lincoln Park                        1441173
Austin-Irving                       1359700
Bezazian                            1357922
Name: ytd, dtype: int64

In [47]:
# gruppieren nach mehreren Spalten

circ_by_year_branch = df.groupby(['year_header','branch'])['ytd'].sum().sort_values(ascending=False)    # Gruppierung nach Jahr und Zweigstelle in [] 
circ_by_year_branch.head(10)

year_header  branch
2011         Harold Washington Library Center    966720
2012         Harold Washington Library Center    937649
2013         Harold Washington Library Center    821749
2014         Harold Washington Library Center    755189
2015         Harold Washington Library Center    694528
2016         Harold Washington Library Center    670077
2017         Harold Washington Library Center    634570
2011         Sulzer Regional                     619734
2012         Sulzer Regional                     615032
2018         Harold Washington Library Center    614313
Name: ytd, dtype: int64

In [48]:
# Nachtrag: Auswahl mit 2-dimensionalem numerischen Index: iloc

# iloc nimmt Indizes [Zeile, Spalte]
# hier 1. Zeile von 1. und vorletzter Spalte

print(f"Branch: {df.iloc[0,0]} \nYTD circ: {df.iloc[0,-2]}")

Branch: Albany Park
YTD circ: 120059

In [49]:
# Auswahl mit Zeilenindex und Spaltenname: loc

print(f"Branch: {df.loc[0,'branch']} \nYTD circ: {df.loc[0, 'ytd']}")

Branch: Albany Park
YTD circ: 120059

In [50]:
type(circ_by_branch_sorted)    # gefilterter Subdatensatz ist aktuell eine Datenreihe (Series)

pandas.Series

In [51]:
# wieder zu Dataframe machen

circ_df = circ_by_branch_sorted.to_frame()
circ_df.head(5)

                                      ytd
branch
Harold Washington Library Center  7498041
Sulzer Regional                   5089225
Lincoln Belmont                   1850964
Edgewater                         1668693
Logan Square                      1539816

In [52]:
# speichern als csv

circ_df.to_csv("circ_by_branch.csv")

In [ ]:
# Übung 9: Anzeigen von Zeilen und Spalten

#1
df['city']

#2
df[10:21]

#3 
df['zip code'][20:31]

In [ ]:
# Übung 10: Auswahl mit loc()

#1
df['zip code'].unique()

#2
df['zip code'].nunique()

In [ ]:
# Übung 11: Wie viele unterschiedliche Werte gibt es?

#1
df.groupby('zip code')['ytd'].mean()

#2
df.groupby('zip code')['ytd'].mean().sort_values()

In [ ]:
# Übung 12: Teildatensätze auswählen durch Gruppierung

#1
df.groupby('zip code')['ytd'].mean()

#2
df.groupby('zip code')['ytd'].mean().sort_values()